name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - run: |
          npm i && npm run all
      - uses: ./
        with:
          issue_number: 10
          hackathon_end: "10/17/2022 22:08:23"
          my_token: ${{ secrets.GITHUB_TOKEN }}
